### ISSUE TITLE
Consider merging changes from https://github.com/AlisterH/gwhere-catalog

### ISSUE THREAD

**Issue by AlisterH** [wdlkmpx/gwhere#1]
Hi, it's good to see someone working on gwhere.
If you haven't seen it, I did a (very) little bit of work on it years ago over at google code, after applying the debian patches.
There was another project there called gwhere so I had to call the repository gwhere-catalog.
It might be worth checking out those changes and merging any useful ones into yours - even if it's just the English improvements.
I see someone else also brought it over from google code to github, but they haven't done any changes of their own.

**Comment by wdlkmpx** [comment]
I think most of the patches no longer apply, all the autotools stuff has been removed, it has to be generated with ./autogen.sh ... this works in distros as old as ubuntu lucid probably, a generated tarball or release may compile in older distros. I think I once ran ./autogen.sh in debian stretch and compiled gwhere in pup 431 just to test the limits.

Some things seem to be broken in modern distros. so I decided to remove gtk1 support & the email stuff. Other e.x.t.e.n.s.i.v.e cleanups and gtk updates happened to make the code less messy, but there might be side effects. Updating this is extremely hard. Gtk2 is the end of the road.

I'll see what I can merge from your repo.

**Comment by wdlkmpx** [comment]
I ported all the applicable changes: a9c9e497c4254d815aaee39452aa0e740bfd2901

I also created the first W release
https://github.com/wdlkmpx/gwhere/releases/

**Comment by wdlkmpx** [comment]
gwhere.pot is generated using a command, so changes to that file will be overwritten.

There seems to be too many translatable strings, here is a list including filename and line number, these are the strings to fix:
[gwhere.translatable.string.txt.zip](https://github.com/wdlkmpx/gwhere/files/6290186/gwhere.translatable.string.txt.zip)

That info may become outdated if the files are modified.
